server:
  port: 8081
spring:
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.115.18:8848
        namespace: 64ed9ca7-d705-4655-b4e4-f824e420a12a
        group: test
        # 在dev环境进行debug时，可以将时间设置长一些
        #heart-beat-interval: 1000 #心跳间隔。单位为毫秒,默认5*1000
        heart-beat-timeout: 300000 #心跳暂停,收不到心跳，会将实例设为不健康。单位为毫秒,默认15*1000
        ip-delete-timeout: 4000000 #Ip删除超时,收不到心跳，会将实例删除。单位为毫秒,默认30*1000

  #sharding-jdbc 水平分表规则配置
  # 数据源名称，多数据源逗号隔开
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3307/sharding-tx-storage?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: lhzlx

    # 水平分表：tb_storage_1/2/3，多个表进行分表时，依次在tables标签后写逻辑
    # tb_storage_1/2/3 为数据库中的事实表
    # tb_storage为编写SQL中操作的逻辑表，sharding-jdbc会自动根据策略操作事实表

    # 配置节点分布情况
    sharding:
      tables:
        tb_storage:
          actual-data-nodes: m1.tb_storage_$->{1..3}
          # 指定tb_storage表的主键生成策略为SNOWFLAKE
          key-generator.column: id
          key-generator.type: SNOWFLAKE
          # 指定tb_storage表的分片策略，分片策略包括分片键和分片算法， tb_storage_1/2/3 所有对3取余
          table-strategy.inline.sharding-column: id
          table-strategy.inline.algorithm-expression: tb_storage_$->{id % 3+1}


    # 打开sql输出日志
    props:
      sql:
        show: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务组的名称，对应service.vgroupMapping.default_tx_group=xxx中配置的default_tx_group
  tx-service-group: default_tx_group
  # 配置事务组与集群的对应关系
  service:
    vgroup-mapping:
      # default_tx_group为事务组的名称，default为集群名称
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 162.14.115.18:8848
      group: SEATA_GROUP
      namespace: 64ed9ca7-d705-4655-b4e4-f824e420a12a
      username: nacos
      password: nacos
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 162.14.115.18:8848
      group: SEATA_GROUP
      namespace: 64ed9ca7-d705-4655-b4e4-f824e420a12a
      username: nacos
      password: nacos
      data-id: seataServer.properties
